### ISSUE TITLE
Set min-height on firepad container.

### ISSUE THREAD

**Issue by mikelehen** [firebase/firepad#171]
Right now if you just copy/paste the "dependencies" and "initializing firepad" snippets from http://www.firepad.io/docs/ the editor is broken because the firepad div isn't big enough.

**Comment by nirleka** [comment]
I also got this problem but after adding css rule below, it worked.

```css
html { 
    height: 100%;
}
body {
     height: 100%; width: 100%;
}
#firepad-container {
     height: 100%; width: 100%;
}
```
